name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django_job:
    uses: codingforentrepreneurs/Django-Kubernetes/.github/workflows/test-django.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      DJANGO_SECRET_KEY: test-key-not-good-maybe-make-one-better
      CLUSTER_NAME: django-k8s
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Insall doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN_KEY }}
    - name: Login to DO Container Registry with short-lived creds
      run: doctl registry login --expiry-seconds 1200
    - name: Build container image
      working-directory: ./web
      run: |
        docker build -f Dockerfile \
          -t registry.digitalocean.com/cfe-k8s/django-k8s-web:latest \
          -t registry.digitalocean.com/cfe-k8s/django-k8s-web:${GITHUB_SHA::7} \
          .
    - name: Push image
      run: |
        docker push registry.digitalocean.com/cfe-k8s/django-k8s-web --all-tags
    - name: K8s cluster kubeconfig file with/ short-lived creds
      run: |
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
    - name: Update Deployment image
      run: |
        kubectl set image deployment/django-k8s-web-deployment django-k8s-web=registry.digitalocean.com/cfe-k8s/django-k8s-web:${GITHUB_SHA::7}
    - name: Wait for rollout to finish
      run: |
        kubectl rollout status deployment/django-k8s-web-deployment
    - name: Migrate Database Command
      run: |
        export SINGLE_POD_NAME=$(kubectl get pod -l app=django-k8s-web-deployment -o jsonpath="{.items[0].metadata.name}")
        kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh
    